services:
  angular:
    image: "report-angular"
    ports:
      - "4200:4200"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
  web:
    image: "nginx"
    depends_on:
      - "angular"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - "angular"
