services:
  angular:
    environment:
      - PORT=4200
    build:
      context: ./ANGULAR-ReportTracker/
      dockerfile: Dockerfile
    ports: 
      - "4200:4200"
  web:
    image: "nginx"
    depends_on:
      - "angular"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - "angular"
  authentication-service:
    build:
      context: ./NET-WebAPI/microservices/WebAPI-Authentication/WebAPI-Authentication/
      dockerfile: Dockerfile
    ports: 
      - "5001:5001"
  product-service:
    build:
      context: ./NET-WebAPI/microservices/WebAPI-ProductService/WebAPI-ProductService/
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
  publish-service:
    build:
      context: ./NET-WebAPI/microservices/WebAPI-Publisher/WebAPI-Publisher/
      dockerfile: Dockerfile
    ports: 
      - "5002:5002"